controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_sorties_list:
    path: /api/events
    controller: 'App\Controller\Api\ApiController::index'
    methods: ['GET']